/* eslint-disable */
/*
 * This file is autogenerated. DO NOT MODIFY BY HAND!
 * Run the @clutch-sh/tools registerWorkflows target instead
*/
import { default as echoDemoEcho} from "@echo-demo/echo";

const registeredWorkflows = {
  "@echo-demo/echo": echoDemoEcho,
};
export default registeredWorkflows;